domain:
    lists:
        - www.baidu.com
        - www.google.com
    list: www.baidu.com/,www.google.com/


spring:
    redis:
        host: 127.0.0.1
        port: 6379
        timeout: 3000
        select: 1
#    redis: